Orgs = [
    "casbin",
    "casdoor",
    "casnode",
    "casbin-cpp",
    "casbin-js",
    "casbin-net",
    "casbin-rs",
    "casbin4d",
    "jcasbin",
    "node-casbin",
    "pycasbin",
    "casbin-lua"
]
IgnoreRepos = [
    "casbin/casbin.github.io",
    "casbin/casbin.io",
    "casbin/casibase.github.io",
    "casbin/caswaf.github.io",
    "casdoor/casdoor.github.io",
    "casnode/casnode.github.io",
    "casbin/casvisor.github.io",
    "casbin/caswire.github.io",
    "casbin/static",
    "casbin/openstack-patron",
    # abandoned
    "casbin/casbin-website",
    "casbin-lua/apisix-authz",
    "casbin/Summer2021",
    "casbin/Summer2022",
    "casbin/Summer2023",
    "casbin/SummerOfCode2023",
    "jcasbin/jfinal-demo",
    "casbin/casdoor", # duplicated with casdoor/casdoor
]
FileTypes = [
    ".md",
    ".mdx",
    ".js",
    ".css",
    ".scss",
    ".less",
    ".sass",
    ".jsx",
    ".tsx",
    ".vue",
    ".go",
    ".ts",
    ".cpp",
    ".h",
    ".hpp",
    ".cs",
    ".rs",
    ".java",
    ".py",
    ".lua",
    ".rb",
    ".php",
    ".c",
    ".swift",
    ".kt",
    ".scala",
    ".dart",
    ".sh",
    ".yml",
    ".yaml",
    ".json"
]
IgnoreFilePatterns = [
    ".min.", # such as swagger-ui.min.js and swagger-ui.min.css
    "test",
    "package-lock.json",
    "conf.go" # https://github.com/casbin/casnode/blob/master/discuzx/conf.go#L19
]
IgnoreDirPatterns = [
    "swagger",
    "test",
    "static/js", # such as https://github.com/casbin/casbin-website-v2/tree/master/static/js
    "wwwroot/lib", # https://github.com/casdoor/casdoor-dotnet-sdk-example/tree/master/MvcApp/wwwroot/lib
    "samples",
]
IgnoreURLPatterns = [
    # temporarily disabled
    "https://www.opensource.org",
    "https://crates.io",
    "https://mvnrepository.com",

    "https?://localhost",
    "https?://127.0.0.1",
    "https?://0.0.0.0",
    # need login
    "https://twitter.com",
    "https://www.linkedin.com",
    "https://open-dev.dingtalk.com",
    "https://nuget.pkg.github.com", # such as https://nuget.pkg.github.com/casbin-net/index.json
    "https://developer.gitter.im/",
    "http://qy.baidu.com/index.html#applist",
    "http://id.qy.baidu.com/static/ge/login.html#/",
    "https://my.visualstudio.com",
    "https://www.amazon.com/ap/oa", # casdoor/casdoor
    "https://usercenter.console.aliyun.com", # casdoor/go-sms-sender

    # api
    "https?://api", # such as https://api.github.com
    "https?://[\\w.]*/api/", # such as https://gitee.com/api/v5/
    "https://translation.googleapis.com",
    "https://groups.google.com/g/",
    "https://github.com/login/oauth",
    "http://chenweihao.vip:8081/callback", # casdoor/casdoor-android-sdk-old
    "https://door.casdoor.com/cas/casbin/cas-java-app/samlValidate",
    "https://challenges.cloudflare.com/turnstile/v0/siteverify", # casdoor/casdoor
    "https://www.linkedIn.com/oauth/v2/accessToken", # casdoor/casdoor
    "http://afs.aliyuncs.com", # casdoor/casdoor
    "https://graph.facebook.com", # casdoor/casdoor
    "https://typetalk.com/oauth2/authorize", # casdoor/casdoor
    "http://auth0.com/authorize", # casdoor/casdoor
    "https://login.eveonline.com/oauth/authorize", # casdoor/casdoor
    "https://gitlab.com/oauth/token", # casdoor/casdoor
    "https://connect.stripe.com/oauth/authorize", # casdoor/casdoor
    "https://gitee.com/oauth/token", # casdoor/casdoor
    "https://www.patreon.com/oauth2/authorize", # casdoor/casdoor
    "https://www.gravatar.com/avatar/", # casdoor/casdoor
    "https://www.googleapis.com", # casdoor/casdoor
    "https://github.com/casdoor/casdoor/releases/tag/", # casdoor/casdoor
    "https://cloud.digitalocean.com/v1/oauth/authorize", # casdoor/casdoor
    "https://github.com/organizations/xxx/settings/applications/1234567", # casdoor/casdoor
    "https://www.strava.com/oauth/authorize", # casdoor/casdoor
    "https://myshopify.com/admin/oauth/authorize", # casdoor/casdoor
    "https://app.intercom.com/oauth", # casdoor/casdoor
    "https://www.dropbox.com/oauth2/authorize", # casdoor/casdoor
    "https://openapi.baidu.com/oauth/2.0/token", # casdoor/casdoor
    "https://login.cloudfoundry.org/oauth/authorize", # casdoor/casdoor
    "https://himg.bdimg.com/sys/portrait/item", # casdoor/casdoor
    "https://access.line.me/oauth2", # casdoor/casdoor
    "https://www.tumblr.com/oauth2", # casdoor/casdoor
    "https://open.feishu.cn/open-apis", # casdoor/casdoor
    "https://oauth.vk.com/authorize", # casdoor/casdoor
    "https://accounts.google.com/o/oauth2/token", # casdoor/casdoor
    "https://login.uber.com/oauth/v2/authorize", # casdoor/casdoor
    "https://open.feishu.cn/open-apis/authen/v1/access_token", # casdoor/casdoor
    "http://specs.openid.net/auth", # casdoor/casdoor
    "https://gitlab.com/oauth/authorize", # casdoor/casdoor
    "https://login.salesforce.com/services/oauth2/authorize", # casdoor/casdoor
    "https://id.twitch.tv/oauth2/authorize", # casdoor/casdoor
    "https://oauth.battlenet.com.cn/authorize", # casdoor/casdoor
    "https://www.facebook.com/dialog/oauth", # casdoor/casdoor
    "https://bitbucket.org/site/oauth2/authorize", # casdoor/casdoor
    "https?://openapi.baidu.com/oauth/2.0/authorize", # casdoor/casdoor
    "https://secure.meetup.com/oauth2/authorize", # casdoor/casdoor

    # doc site
    "https?://your-casdoor-url.com",
    "https?://[a-z]*.?your-site-url.com",
    "https://flarum.org/",
    "https://dash.cloudflare.com/",
    "https://developer.android.com",
    "https://developer.twitter.com",
    "https://www.epis2048.net",
    "https://codeigniter.com/",
    "https://www.thinkphp.cn/",
    "http://yourip",
    "http://your-ip",
    "http://APISIX_HOSTNAME",
    "http://BACKEND_HOSTNAME",
    "http://JENKINS_HOSTNAME",
    "https://REDIRECT_URI",
    "http://CASDOOR_HOSTNAME", # also https://github.com/casdoor/casdoor-spring-boot-shiro-example
    "http://your_endpoint", # casbin-website-v2
    "https://github.com/[\\w\\d/-]*/edit/", # such as https://github.com/casbin/caswaf-website/edit/master/${blogDirPath}/${blogPath}
    "https://attachment.discuz.net/forum/", # casnode/casnode-website
    "http://test.casbin.com", # casdoor/odoo-casdoor-oauth
    "http://YOUR_DOMAIN_NAME",
    "https://cdn.casbin.com/",
    "http://FRONTEND_HOSTNAME",
    "https://oauth-openshift.apps.",
    "http://schemas.microsoft.com",
    "https://www.google.com/a/",
    "http://schemas.android.com",
    "http://GITLAB_HOSTNAME",

    # https://github.com/casdoor/casdoor
    "https://cloud.example.org",
    "https://xxx",
    "https://media.licdn.cn/dms/image/",

    # https://github.com/casdoor/casdoor-dotnet-sdk
    # https://github.com/casbin-net/casbin-aspnetcore
    # https://github.com/casdoor/casdoor
    "https?://example.com",

    # https://github.com/casdoor/traefik-casdoor-auth
    "http://webhook.domain.local",

    # https://github.com/casdoor/wordpress-casdoor-plugin
    "http://your-wordpress-domain",

    # https://github.com/casbin/casbin-mesh
    "http://node",

    # https://github.com/node-casbin
    "https?://admin",

    # https://github.com/casbin/hraft-dispatcher
    "https://testing",

    # https://github.com/casbin/k8s-gatekeeper
    "https://webhook.domain.local",
    "https://kubernetes.docker.internal",

    # casbin/casbin-mp
    "https?://192.168",
    "https://door.example.in",

    # casbin-cpp/nginx-casbin-module
    "http://ip:port",

    # casbin/session-role-manager
    "https://en.wikipedia.org/wiki/Session_\\(computer_science",

    # node-casbin/etcd-watcher
    "https://github.com/coreos/etcd/releases/download/",

    # pycasbin/flask-authz
    "https://github.com/pycasbin/flask-authz/tarball/v",

    # casdoor/casdoor-java-sdk
    "http://forum.casbin.org?code=xxx&state=yyyy",

    # casbin/casbin.js
    "http://Domain_name/casbin/api",

    # casbin/auth0-role-manager
    "https://abc.us.webtask.io",

    # opencollective
    "https://opencollective.com/casbin/sponsor/",

    # demo site
    "https://demo.ai.casbin.com/",
    "https://demo-ai.casbin.com",
    "https://demo.caswaf.com",

    # xmlns
    "http://www.yale.edu/tp/cas", # casdoor/casdoor

    # rpc url
    "https://mainnet.infura.io", # casdoor/casdoor
    "https://goerli.infura.io", # casdoor/casdoor
    "https://matic-mumbai.chainstacklabs.com", # casdoor/casdoor
    "https://bsc-dataseed.binance.org/", # casdoor/casdoor
    "https://mainnet.optimism.io", # casdoor/casdoor
    "https://rpc.ankr.com/arbitrum", # casdoor/casdoor

    # unknown usage
    "https://error:", # casdoor/casdoor
    "https://pay.com/pay.php", # casdoor/casdoor

    # response example or code explanation
    "https://media.licdn.cn/dms/image/C5603AQHbdR8RkG62yg/profile-displayphoto-shrink_100_100/0/1625279434135?e=1630540800&v=beta&t=Z-bQKf_jFv8L1uwr6X5AJLoTQRWZrueT7qrITDSvxWM", # casdoor/casdoor
    "http://tp1.sinaimg.cn/1404376560/50/0/1", # casdoor/casdoor
    "http://i0.hdslb.com/bfs/face/e1c99895a9f9df4f260a70dc7e227bcb46cf319c.jpg", # casdoor/casdoor
    "https://duo.com/logo.png", # casdoor/casdoor
]
UA = "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36 Edg/116.0.1938.76"