Orgs = [
    "casbin",
    "casdoor",
    "casnode",
    "casbin-cpp",
    "casbin-js",
    "casbin-net",
    "casbin-rs",
    "casbin4d",
    "jcasbin",
    "node-casbin",
    "pycasbin",
    "casbin-lua"
]
IgnoreRepos = [
    "casbin/casbin.io",
    "casbin/casibase.github.io",
    "casbin/caswaf.github.io",
    "casdoor/casdoor.github.io",
    "casnode/casnode.github.io",
    "casbin/casbin-website",
    "casbin/static",
    "casbin/openstack-patron",
]
FileTypes = [
    ".md",
    ".mdx",
    ".js",
    ".css",
    ".scss",
    ".less",
    ".sass",
    ".jsx",
    ".tsx",
    ".vue",
    ".go",
    ".ts",
    ".cpp",
    ".h",
    ".hpp",
    ".cs",
    ".rs",
    ".java",
    ".py",
    ".lua",
    ".rb",
    ".php",
    ".c",
    ".swift",
    ".kt",
    ".scala",
    ".dart",
    ".sh",
    ".yml",
    ".yaml",
    ".json"
]
IgnoreFilePatterns = [
    ".min.", # such as swagger-ui.min.js and swagger-ui.min.css
    "test"
]
IgnoreDirPatterns = [
    "swagger",
    "test"
]
IgnoreURLPatterns = [
    "https?://localhost",
    "https?://127.0.0.1",
    "https?://0.0.0.0",
    # need login
    "https://twitter.com",
    "https://www.linkedin.com",
    "https://open-dev.dingtalk.com",

    # api
    "https?://api", # such as https://api.github.com
    "https?://[\\w.]*/api/", # such as https://gitee.com/api/v5/


    # doc site
    "https?://your-casdoor-url.com",
    "https?://[a-z]*.?your-site-url.com",
    "https://flarum.org/",
    "https://dash.cloudflare.com/",
    "https://developer.android.com",
    "https://developer.twitter.com",
    "https://www.epis2048.net",
    "https://codeigniter.com/",
    "https://www.thinkphp.cn/",
    "http://yourip",
    "http://your-ip",
    "http://APISIX_HOSTNAME",
    "http://BACKEND_HOSTNAME",
    "http://JENKINS_HOSTNAME",
    "https://REDIRECT_URI",
    "http://CASDOOR_HOSTNAME", # also https://github.com/casdoor/casdoor-spring-boot-shiro-example
    "http://your_endpoint", # casbin-website-v2

    # https://github.com/casdoor/casdoor
    "https://cloud.example.org",
    "https://xxx",

    # https://github.com/casdoor/casdoor-dotnet-sdk
    # https://github.com/casbin-net/casbin-aspnetcore
    # https://github.com/casdoor/casdoor
    "https?://example.com",

    # https://github.com/casdoor/traefik-casdoor-auth
    "http://webhook.domain.local",

    # https://github.com/casdoor/wordpress-casdoor-plugin
    "http://your-wordpress-domain",

    # https://github.com/casbin/casbin-mesh
    "http://node",

    # https://github.com/node-casbin
    "https?://admin",


    # https://github.com/casbin/hraft-dispatcher
    "https://testing",

    # https://github.com/casbin/k8s-gatekeeper
    "https://webhook.domain.local",
    "https://kubernetes.docker.internal",

    # casbin/casbin-mp
    "https?://192.168",
    "https://door.example.in",
]
