name: Weekly Check

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * 6" # runs every saturday at 12:00 UTC

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.20'

      - name: Check
        run: go run main.go --week

      - name: Upload Report
        uses: actions/upload-artifact@v3
        with:
          name: report
          path: report*.md
          if-no-files-found: error
